### ISSUE TITLE
Gnome 47 support

### ISSUE THREAD

**Issue by EvanWashkow** [brunodrugowick/notification-position-gnome-extension#22]
https://extensions.gnome.org/extension/4105/notification-banner-position/ currently lists support up to Gnome 46. Gnome 47 support would be greatly appreciated. Thanks in advance!

**Comment by brunodrugowick** [comment]
Opa, I'll take a look at this tonight or during the weekend. Thanks for opening the issue and letting me know.

**Comment by brunodrugowick** [comment]
Pushed a new version to the Gnome Extensions website, should be quickly approved now. Took me some time because I had to update a deprecated version of the automation I have in place to support new Gnome versions.

EDIT: the problem was not the update itself, just had to get to a proper computer instead of doing it on a smartphone 😅 

![image](https://github.com/user-attachments/assets/7e34c07f-b725-4343-ad4f-4fb8ab312fcc)

**Comment by brunodrugowick** [comment]
Done.
